INSERT INTO Ingredient VALUES ('FLTO', 'Flour Tortilla' , 'WRAP');
INSERT INTO Ingredient VALUES ('COTO', 'Corn Tortilla' , 'WRAP');
INSERT INTO Ingredient VALUES ('GRBF', 'Ground Beef' , 'PROTEIN');
INSERT INTO Ingredient VALUES ('CARN', 'Carnitas' , 'PROTEIN');
INSERT INTO Ingredient VALUES ('TMTO', 'Diced Tomatoes' , 'VEGGIES');
INSERT INTO Ingredient VALUES ('LETC', 'Lettuce' , 'VEGGIES');
INSERT INTO Ingredient VALUES ('CHED', 'Cheddar' , 'CHEESE');
INSERT INTO Ingredient VALUES ('JACK', 'Monterrey Jack' , 'CHEESE');
INSERT INTO Ingredient VALUES ('SLSA', 'Salsa' , 'SAUCE');
INSERT INTO Ingredient VALUES ('SRCR', 'Sour Cream' , 'SAUCE');
--INSERT INTO user (username, password, fullname, street, city, state, zip, phone_number) VALUES ('Alice', '123', 'Alice', 'Test', 'Test', 'Test', '1234567890');
--INSERT INTO user (username, password, fullname, street, city, state, zip, phone_number) VALUES ('Alexander', '123', 'Alexander', 'Test', 'Test', 'Test', '0987654321');